### ISSUE TITLE
EventEmitter#once is not only called once

### ISSUE THREAD

**Issue by double-daruma** [coreybutler/tappedout#4]
**How To Reproduce:**
```js
let ee = new EventEmitter();
ee.once("bar", () => console.log("bar happend"))
ee.emit("bar")
ee.emit("bar")
```
"bar happend" is printed twice

**Expected Behavior:**
"bar happend" should be printed once

**Comment by coreybutler** [comment]
Thanks for reporting. This does look like a bug.

Note to self: handler is not removed at https://github.com/coreybutler/tappedout/blob/6cf8134ff23a851314f91e55118c0ceeaf8c3601/lib/runner.js#L32
